query GwObtains {
  gwObtains {
    id
    cat
    type
    flavor
    box
    lb
    lockBoxId
    rep
    lockBox {
      id
      name
      rarity
    }
  }
}

query GwObtain($id: Int!) {
  gwObtain(id: $id) {
    id
    cat
    type
    flavor
    box
    lb
    lockBoxId
    rep
    createdAt
    updatedAt
    lockBox {
      id
      name
      rarity
      type
    }
  }
}

query GwObtainByKey($cat: String!, $type: String!, $flavor: String!) {
  gwObtainByKey(cat: $cat, type: $type, flavor: $flavor) {
    id
    cat
    type
    flavor
    box
    lb
    rep
    lockBox {
      id
      name
    }
  }
}
