query Ships {
  ships {
    id
    name
    description
    image
    released
    faction
    factionLede
    facSort
    rank
    rankLevel
    tier
    type
    hull
    hullMod
    shieldMod
    turnRate
    impulse
    inertia
    foreWeapons
    aftWeapons
    tacticalSlots
    engineeringSlots
    scienceSlots
    secondaryDeflector
    hangars
    devices
    experimental
    uniconsole
    uniconsoleId
    cost
    displayPrefix
    displayClass
    displayType
    shipType {
      id
      name
    }
  }
}

query Ship($id: Int!) {
  ship(id: $id) {
    id
    name
    description
    image
    image2
    released
    internalName
    fc
    faction
    facSort
    rank
    rankLevel
    tier
    upgradeCost
    type
    hull
    hullMod
    shieldMod
    turnRate
    impulse
    inertia
    powerAll
    powerWeapons
    powerShields
    powerEngines
    powerAuxiliary
    powerBoost
    boffs
    foreWeapons
    aftWeapons
    equipCannons
    devices
    tacticalSlots
    engineeringSlots
    scienceSlots
    uniconsole
    t5uConsole
    experimental
    secondaryDeflector
    hangars
    cost
    abilities
    admiraltyEng
    admiraltyTac
    admiraltySci
    displayPrefix
    displayClass
    displayType
    factionLede
    uniconsoleId
    shipTypeId
    createdAt
    updatedAt
    shipType {
      id
      name
    }
    uniConsole {
      id
      name
      rarity
      type
    }
    starshipTraits {
      id
      name
      short
      type
      obtained
    }
  }
}

query ShipByName($name: String!) {
  shipByName(name: $name) {
    id
    name
    description
    image
    image2
    released
    internalName
    fc
    faction
    facSort
    rank
    rankLevel
    tier
    upgradeCost
    type
    hull
    hullMod
    shieldMod
    turnRate
    impulse
    inertia
    powerAll
    powerWeapons
    powerShields
    powerEngines
    powerAuxiliary
    powerBoost
    boffs
    foreWeapons
    aftWeapons
    equipCannons
    devices
    tacticalSlots
    engineeringSlots
    scienceSlots
    uniconsole
    t5uConsole
    experimental
    secondaryDeflector
    hangars
    cost
    abilities
    admiraltyEng
    admiraltyTac
    admiraltySci
    displayPrefix
    displayClass
    displayType
    factionLede
    uniconsoleId
    shipTypeId
    createdAt
    updatedAt
    shipType {
      id
      name
    }
    uniConsole {
      id
      name
      rarity
      type
    }
    starshipTraits {
      id
      name
      short
      type
      obtained
    }
  }
}
