query StarshipTraits {
  starshipTraits {
    id
    name
    short
    basic
    detailed
    type
    obtained
    iconName
    tag
    tag2
    tag3
    ships {
      id
      name
      faction
      factionLede
      facSort
      displayClass
      displayPrefix
      displayType
      cost
    }
  }
}

query StarshipTrait($id: Int!) {
  starshipTrait(id: $id) {
    id
    name
    short
    basic
    detailed
    type
    obtained
    iconName
    tag
    tag2
    tag3
    createdAt
    updatedAt
    ships {
      id
      name
      faction
      factionLede
      facSort
      displayClass
      displayPrefix
      displayType
      tier
      type
      cost
    }
    publicBuildCount
  }
}

query StarshipTraitByName($name: String!) {
  starshipTraitByName(name: $name) {
    id
    name
    short
    basic
    detailed
    type
    obtained
    ships {
      id
      name
      faction
      factionLede
      facSort
      displayClass
      displayPrefix
      displayType
      cost
    }
  }
}
