type Ship {
  id: Int!
  name: String!
  description: String
  image: String
  image2: String
  released: String
  internalName: String
  fc: Boolean!
  faction: String
  facSort: String
  rank: String
  rankLevel: Int
  tier: Int
  upgradeCost: String
  type: String
  hull: String
  hullMod: Float
  shieldMod: Float
  turnRate: Float
  impulse: Float
  inertia: Int
  powerAll: Int
  powerWeapons: Int
  powerShields: Int
  powerEngines: Int
  powerAuxiliary: Int
  powerBoost: Int
  boffs: String
  foreWeapons: Int
  aftWeapons: Int
  equipCannons: Boolean
  devices: Int
  tacticalSlots: Int
  engineeringSlots: Int
  scienceSlots: Int
  uniconsole: String
  t5uConsole: String
  experimental: Boolean!
  experimentalWeapon: String
  secondaryDeflector: Boolean!
  hangars: Int
  cost: String
  abilities: String
  admiraltyEng: Int
  admiraltyTac: Int
  admiraltySci: Int
  displayPrefix: String
  displayClass: String
  displayType: String
  factionLede: String
  wikiName: String!
  rawData: JSON
  createdAt: DateTime!
  updatedAt: DateTime!
  shipTypeId: Int
  uniconsoleId: Int
  experimentalWeaponId: Int
  shipType: ShipType
  uniConsole: Infobox
  experimentalWeaponItem: Infobox
  starshipTraits: [StarshipTrait!]!
  publicBuildCount: Int!
}

extend type Query {
  ships: [Ship!]!
  ship(id: Int!): Ship
  shipByName(name: String!): Ship
}
